[2025-10-30T07:17:24.440+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.load_task manual__2025-10-30T07:17:15.406317+00:00 [queued]>
[2025-10-30T07:17:24.446+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.load_task manual__2025-10-30T07:17:15.406317+00:00 [queued]>
[2025-10-30T07:17:24.446+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-10-30T07:17:24.459+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_task> on 2025-10-30 07:17:15.406317+00:00
[2025-10-30T07:17:24.463+0000] {standard_task_runner.py:57} INFO - Started process 4521 to run task
[2025-10-30T07:17:24.466+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'load_task', 'manual__2025-10-30T07:17:15.406317+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpcaa7obgn']
[2025-10-30T07:17:24.467+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask load_task
[2025-10-30T07:17:24.505+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.load_task manual__2025-10-30T07:17:15.406317+00:00 [running]> on host codespaces-497b64
[2025-10-30T07:17:24.589+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T07:17:15.406317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T07:17:15.406317+00:00'
[2025-10-30T07:17:24.590+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T07:17:24.590+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n.import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-transform-data.csv sp_500_sector_count" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-load-db.db']
[2025-10-30T07:17:24.598+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T07:17:24.741+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-30T07:17:24.757+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=load_task, execution_date=20251030T071715, start_date=20251030T071724, end_date=20251030T071724
[2025-10-30T07:17:24.799+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-10-30T07:17:24.809+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
