[2025-10-30T07:17:22.113+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.transform_task manual__2025-10-30T07:17:15.406317+00:00 [queued]>
[2025-10-30T07:17:22.118+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.transform_task manual__2025-10-30T07:17:15.406317+00:00 [queued]>
[2025-10-30T07:17:22.118+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-10-30T07:17:22.130+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform_task> on 2025-10-30 07:17:15.406317+00:00
[2025-10-30T07:17:22.133+0000] {standard_task_runner.py:57} INFO - Started process 4504 to run task
[2025-10-30T07:17:22.137+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'transform_task', 'manual__2025-10-30T07:17:15.406317+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp94f2gd8x']
[2025-10-30T07:17:22.137+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask transform_task
[2025-10-30T07:17:22.164+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.transform_task manual__2025-10-30T07:17:15.406317+00:00 [running]> on host codespaces-497b64
[2025-10-30T07:17:22.202+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T07:17:15.406317+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-30T07:17:15.406317+00:00'
[2025-10-30T07:17:22.377+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-10-30T07:17:22.381+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=challenge_dag, task_id=transform_task, execution_date=20251030T071715, start_date=20251030T071722, end_date=20251030T071722
[2025-10-30T07:17:22.429+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-10-30T07:17:22.442+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
